# services:
#   - type: web
#     # name: ai-chat-service
#     name: llama-chatbot
#     plan: free
#     dockerfilePath: ./Dockerfile
#     envVars:
#       - key: API_KEY
#         generateValue: true
#       - key: CORS_ALLOWED_ORIGINS
#         value: "https://harmonykloud.com, http://localhost:5173, http://localhost:3000, http://staging.harmonykloud.com"
#     disk:
#       name: models
#       mountPath: /app/models
#       sizeGB: 1  # Max for free tier

services:
  - type: web
    name: llama-chatbot
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: CHATBOT_API_KEY
        generateValue: true
      - key: CORS_ALLOWED_ORIGINS
        value: "*"
    disk:
      name: models
      mountPath: /app/models
      sizeGB: 1
    buildCommand: |
      git submodule update --init --recursive
      docker build -t chatbot .